AWSTemplateFormatVersion: 2010-09-09
Resources:
  LF2:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: 'python3.8'
      Handler: 'lambda_handler'
      FunctionName: 'LF2-photo-search'
      Description: 'By CF - LF2 to search for photos'
      Role: 'arn:aws:iam::532016339310:role/service-role/search-photos-LF2-role-93w6vaxe'
      Code:
        S3Bucket: 'assg3-code-bucket'
        S3Key: 'search-photos-LF2.py.zip'